# 导航栏头部名称
nav_name: Chen's Blog

# 站点图标和APP图标
favicon:
  icon: /images/icon.jpg
  touch_icon: /images/icon.jpg
# 是否开启版权声明
copyright:
  enable: true
  author: 陈志昊
  license: '本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议。转载请注明出处！'

# 是否开启 分享功能: https://github.com/overtrue/share.js
social_share:
  enable: true
  sites: qzone, qq, weibo, wechat, douban, google, facebook, twitter
  disabled:



# 开启 评论 & 统计 插件 : https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
leancloud:
  appid: UdjtjgaXj3uYE0OUhftzG7R6-gzGzoHsz # 填写您的appid
  appkey: 3fnNYykrhSbmF72s8P26RcfE # 填写您的appkey
#  comment: true # 是否开启评论系统
#  timer: true # 是否开启文章统计


# 页脚信息
footer:
  start: "2014-10-01"
  more:


# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "8.4.3" # default v7.1.2
  theme: "forest"
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
  #startOnload: true  // default true


# 导航栏选项
# blank: 是否在新页面打开，默认 false
# children：开启二级导航栏
nav:
  - name: 主页
    path: /
  #  -
  #    name: 系列
  #    children:
  #      -
  #        name: Spring学习总结
  #        path: /2019/12/03/Spring学习过程总结/
  #        blank: true
  - name: 归档
    path: /archives/
  - name: 分类
    path: /categories/
  - name: 标签
    path: /tags/
  # -
  #   name: 友链
  #   path: /friends/
  - name: 关于
    path: /about/


# 是否开启 打赏功能
reward:
  enable: false
  meta: 知识 & 情怀 | 二者兼得 # 提示文字
  button_meta: 投食 # 按钮文字
  qrcodes:
    # 支持多个支付方式
    # src: 二维码位置
    # meta: 二维码提示信息
    - src: /images/wechat.png
      meta: "微信扫一扫, 向我投食"
    - src: /images/alipay.png
      meta: "支付宝扫一扫, 向我投食"

# 友链详细信息：支持多个友链
friends:
  - nickname: GodBMW # 昵称
    avatar: https://gravatar.loli.net/avatar/b20750c40cd911256ddbd76a7f7e724c # 头像链接
    site: https://godbmw.com # 站点地址
    meta: BMW 主题作者 # 站点描述