title: Chen's Blog
description: 陈志昊的个人博客
keywords: 陈志昊
url: https://chenzhihao.cc
# 自动生成sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# RSS文件
rss:

# 自定义样式文件
custom_style: /custom/style.css

# 自定义脚本文件
# loc: 脚本文件位置
# load: 加载方式
custom_script:
  - src: /custom/script.js
    load: async

# 是否渲染 文章目录
toc: false

# 是否支持 数学公式
mathjax: true

# 是否开启 音乐组件
player: false

# 友链详细信息
#friends:
#  - nickname: GodBMW
#    avatar: /images/touch-icon.png
#    site: https://godbmw.com
#    meta: 啦啦啦♪(^∇^*)
#    show: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: bmw

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@gitee.com:hzszl/hzszl.git
  branch: master

skip_render:
  - baidu_verify_ICTvbT6BAW.html
  - pdf/**
  - file/**
  - csp/**
  - _posts/致富之路.md